spring.application.name=core
spring.data.mongodb.uri=${MONGO_URI}
bpms.jwt.secret=${JWT_SECRET}

# Para llamar a la IA desde tu futuro servicio
gemini.api.key=AIzaSyDPpBeZhz7z3QXazZTzCTjmQXL6UsPVNmE

# Permitir archivos grandes (hasta 50MB por archivo)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true