spring.application.name=core

# Variables dinámicas que vienen del .env (local) o del servidor (AWS)
spring.data.mongodb.uri=${MONGO_URI}
bpms.jwt.secret=${JWT_SECRET}
gemini.api.key=${GEMINI_API_KEY}

# Permitir archivos grandes (hasta 50MB por archivo)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true