spring.application.name=core
# Obligamos a Spring a leer el .env local
spring.config.import=optional:file:.env[.properties]

# Variables dinámicas
spring.data.mongodb.uri=${MONGO_URI}
bpms.jwt.secret=${JWT_SECRET}
gemini.api.key=${GEMINI_API_KEY}

# Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true